/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "Std_Types.h"
#include "stm32f103x6.h"

#include "core_cm3.h"
#include "RCC/Rcc.h"
#include "Port.h"
#include "Dio.h"
#include "Mcu.h"
#include "Systick.h"
#include  "Gpt/Gpt.h"

#include "Scheduler.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern const Port_ConfigType Port_Config;
Task_ref Task1,Task2 ,Task3;

void task1(void)
{
	while(1)
	{
		Dio_WriteChannel ( GPIOA_ID, DIO_CHANNEL_P13, STD_HIGH );

	}
}
void task2(void)
{
	while(1)
	{
		Dio_WriteChannel ( GPIOA_ID, DIO_CHANNEL_P13, STD_LOW );

	}
}
void task3(void)
{
	while(1)
	{
		Dio_WriteChannel ( GPIOA_ID, DIO_CHANNEL_P13, STD_LOW );

	}
}
int main(void)
{
	Std_ReturnType std_ret =E_OK;
	MYRTOS_errorID rtos_ret=NoError;

	//	Mcu_Init(&Mcu_Config);
	std_ret= Mcu_InitClock(HSI);
	Rcc_GpioA_Enable();
	std_ret=STK_voidInit(CPU_CLK_AHB);
	Port_Init(&Port_Config);
	//    std_ret= Mcu_InitClock(MCU_CLOCKSETTING_HSI);
	//    Gpt_Init(&Gpt_Config[GPT_CHANNEL_TIM2]);
	//    Gpt_Init(&Gpt_Config[GPT_CHANNEL_TIM3]);
	//    uint16 timm=0;
	rtos_ret |= MYRTOS_Init();
	if((std_ret==E_NOT_OK )|| (rtos_ret!=NoError) )
	{
		while(1);
	}
	Task1.Stack_Size=1024;
	Task1.p_TaskEntry=task1;
	Task1.priority=3;
	strcpy(Task1.TaskName ,"task_1");
	Task2.Stack_Size=1024;
	Task2.p_TaskEntry=task2;
	Task2.priority=3;
	strcpy(Task2.TaskName ,"task_2");
	Task3.Stack_Size=1024;
	Task3.p_TaskEntry=task3;
	Task3.priority=3;
	strcpy(Task3.TaskName ,"task_3");
	rtos_ret|=MYRTOS_Create_task(&Task1);
	rtos_ret|=MYRTOS_Create_task(&Task2);
	rtos_ret|=MYRTOS_Create_task(&Task3);

	while (1)
	{
		//    	STK_voidSetBusyWait(5000);
		//    	Gpt_StartTimer(GPT_CHANNEL_TIM2,500);
		//    	Gpt_StopTimer(GPT_CHANNEL_TIM2);
		//    	timm=Gpt_GetTimeElapsed(0);
		//		Dio_WriteChannel ( GPIOA_ID, DIO_CHANNEL_P13, STD_LOW );

		/* DIO layer from here: Dio_WriteChannel / Dio_ReadChannel */
	}
}
